-- 班级宠物屋 PostgreSQL 初始化脚本
-- 执行前请先连接到目标数据库，例如：
--   CREATE DATABASE class_pet_house;
--   \c class_pet_house
--
-- 当前脚本覆盖现行业务表：
-- users, classes, students, groups, score_rules, history,
-- student_total_food_summaries, shop_items, exchange_records, licenses
--
-- 不包含历史临时/备份表，例如 users_backup。

BEGIN;

-- 统一维护 updated_at 的触发器函数
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    activation_code VARCHAR(100),
    is_activated BOOLEAN NOT NULL DEFAULT FALSE,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    settings JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_users_settings_object CHECK (jsonb_typeof(settings) = 'object')
);

CREATE TABLE IF NOT EXISTS classes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL DEFAULT '默认班级',
    system_name VARCHAR(100) NOT NULL DEFAULT '石榴果宠物屋',
    theme VARCHAR(50) NOT NULL DEFAULT 'pink',
    growth_stages JSONB NOT NULL DEFAULT '[0,5,10,20,30,45,60,75,90,100]'::jsonb,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_classes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_classes_growth_stages_array CHECK (jsonb_typeof(growth_stages) = 'array'),
    CONSTRAINT chk_classes_sort_order_non_negative CHECK (sort_order >= 0)
);

CREATE TABLE IF NOT EXISTS groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_groups_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    CONSTRAINT chk_groups_sort_order_non_negative CHECK (sort_order >= 0)
);

CREATE TABLE IF NOT EXISTS students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    pet_type VARCHAR(50),
    pet_name VARCHAR(50),
    food_count INTEGER NOT NULL DEFAULT 0,
    food_reset_at TIMESTAMP,
    total_food_earned INTEGER NOT NULL DEFAULT 0,
    badges JSONB NOT NULL DEFAULT '[]'::jsonb,
    current_badges_count INTEGER NOT NULL DEFAULT 0,
    total_badges_earned INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    group_id INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_students_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    CONSTRAINT fk_students_group FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE SET NULL,
    CONSTRAINT chk_students_badges_array CHECK (jsonb_typeof(badges) = 'array'),
    CONSTRAINT chk_students_food_count_non_negative CHECK (food_count >= 0),
    CONSTRAINT chk_students_total_food_non_negative CHECK (total_food_earned >= 0),
    CONSTRAINT chk_students_current_badges_non_negative CHECK (current_badges_count >= 0),
    CONSTRAINT chk_students_total_badges_non_negative CHECK (total_badges_earned >= 0),
    CONSTRAINT chk_students_sort_order_non_negative CHECK (sort_order >= 0)
);

CREATE TABLE IF NOT EXISTS score_rules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    icon VARCHAR(50) NOT NULL DEFAULT '⭐',
    value INTEGER NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_score_rules_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    CONSTRAINT chk_score_rules_sort_order_non_negative CHECK (sort_order >= 0)
);

CREATE TABLE IF NOT EXISTS history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id INTEGER NOT NULL,
    student_id INTEGER NOT NULL,
    rule_id INTEGER,
    rule_name VARCHAR(50),
    value INTEGER NOT NULL DEFAULT 0,
    type VARCHAR(20) NOT NULL DEFAULT 'score',
    is_revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_history_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    CONSTRAINT fk_history_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT chk_history_type CHECK (type IN ('score', 'graduate', 'exchange', 'revoke'))
);

CREATE TABLE IF NOT EXISTS student_total_food_summaries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id INTEGER NOT NULL,
    student_id INTEGER NOT NULL,
    rule_id INTEGER NOT NULL,
    rule_name VARCHAR(50) NOT NULL,
    award_count INTEGER NOT NULL DEFAULT 0,
    total_food INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_student_total_food_summaries_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    CONSTRAINT fk_student_total_food_summaries_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT uq_student_total_food_summaries_student_rule UNIQUE (class_id, student_id, rule_id),
    CONSTRAINT chk_student_total_food_summaries_award_count_positive CHECK (award_count > 0),
    CONSTRAINT chk_student_total_food_summaries_total_food_positive CHECK (total_food > 0)
);

CREATE TABLE IF NOT EXISTS shop_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(200) NOT NULL DEFAULT '',
    icon VARCHAR(50) NOT NULL DEFAULT '🎁',
    price INTEGER NOT NULL DEFAULT 1,
    stock INTEGER NOT NULL DEFAULT -1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_shop_items_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    CONSTRAINT chk_shop_items_price_positive CHECK (price >= 1),
    CONSTRAINT chk_shop_items_stock_valid CHECK (stock >= -1)
);

CREATE TABLE IF NOT EXISTS exchange_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id INTEGER NOT NULL,
    student_id INTEGER NOT NULL,
    item_id INTEGER,
    item_name VARCHAR(50) NOT NULL,
    cost INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_exchange_records_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    CONSTRAINT fk_exchange_records_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT chk_exchange_records_cost_non_negative CHECK (cost >= 0)
);

CREATE TABLE IF NOT EXISTS licenses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    is_used BOOLEAN NOT NULL DEFAULT FALSE,
    used_by INTEGER,
    used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_licenses_user FOREIGN KEY (used_by) REFERENCES users(id) ON DELETE SET NULL
);

-- 常用索引
CREATE INDEX IF NOT EXISTS idx_classes_user_id ON classes(user_id);
CREATE INDEX IF NOT EXISTS idx_users_is_admin ON users(is_admin);
CREATE INDEX IF NOT EXISTS idx_groups_class_id ON groups(class_id);
CREATE INDEX IF NOT EXISTS idx_students_class_id ON students(class_id);
CREATE INDEX IF NOT EXISTS idx_students_group_id ON students(group_id);
CREATE INDEX IF NOT EXISTS idx_students_class_food_count ON students(class_id, food_count DESC);
CREATE INDEX IF NOT EXISTS idx_students_class_total_food_earned ON students(class_id, total_food_earned DESC);
CREATE INDEX IF NOT EXISTS idx_students_class_current_badges_count ON students(class_id, current_badges_count DESC);
CREATE INDEX IF NOT EXISTS idx_students_class_total_badges_earned ON students(class_id, total_badges_earned DESC);
CREATE INDEX IF NOT EXISTS idx_score_rules_class_id ON score_rules(class_id);
CREATE INDEX IF NOT EXISTS idx_history_class_id ON history(class_id);
CREATE INDEX IF NOT EXISTS idx_history_student_id ON history(student_id);
CREATE INDEX IF NOT EXISTS idx_history_created_at ON history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_student_total_food_summaries_student_id ON student_total_food_summaries(student_id);
CREATE INDEX IF NOT EXISTS idx_student_total_food_summaries_class_student ON student_total_food_summaries(class_id, student_id);
CREATE INDEX IF NOT EXISTS idx_student_total_food_summaries_class_total_food ON student_total_food_summaries(class_id, total_food DESC);
CREATE INDEX IF NOT EXISTS idx_shop_items_class_id ON shop_items(class_id);
CREATE INDEX IF NOT EXISTS idx_exchange_records_class_id ON exchange_records(class_id);
CREATE INDEX IF NOT EXISTS idx_exchange_records_student_id ON exchange_records(student_id);
CREATE INDEX IF NOT EXISTS idx_exchange_records_created_at ON exchange_records(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_licenses_used_by ON licenses(used_by);

-- updated_at 触发器
DROP TRIGGER IF EXISTS trg_users_set_updated_at ON users;
CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_classes_set_updated_at ON classes;
CREATE TRIGGER trg_classes_set_updated_at
BEFORE UPDATE ON classes
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_groups_set_updated_at ON groups;
CREATE TRIGGER trg_groups_set_updated_at
BEFORE UPDATE ON groups
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_students_set_updated_at ON students;
CREATE TRIGGER trg_students_set_updated_at
BEFORE UPDATE ON students
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_score_rules_set_updated_at ON score_rules;
CREATE TRIGGER trg_score_rules_set_updated_at
BEFORE UPDATE ON score_rules
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_history_set_updated_at ON history;
CREATE TRIGGER trg_history_set_updated_at
BEFORE UPDATE ON history
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_student_total_food_summaries_set_updated_at ON student_total_food_summaries;
CREATE TRIGGER trg_student_total_food_summaries_set_updated_at
BEFORE UPDATE ON student_total_food_summaries
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_shop_items_set_updated_at ON shop_items;
CREATE TRIGGER trg_shop_items_set_updated_at
BEFORE UPDATE ON shop_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_exchange_records_set_updated_at ON exchange_records;
CREATE TRIGGER trg_exchange_records_set_updated_at
BEFORE UPDATE ON exchange_records
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_licenses_set_updated_at ON licenses;
CREATE TRIGGER trg_licenses_set_updated_at
BEFORE UPDATE ON licenses
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 表注释
COMMENT ON TABLE users IS '系统用户表，保存教师账号、密码哈希、激活状态、管理员标记和个性化设置。';
COMMENT ON TABLE classes IS '班级表，保存每个用户创建的班级、主题和成长阶段配置。';
COMMENT ON TABLE groups IS '班级分组表，用于小组管理和随机分组。';
COMMENT ON TABLE students IS '学生表，保存学生姓名、宠物信息、积分和徽章数据。';
COMMENT ON TABLE score_rules IS '积分规则表，保存班级内可配置的加分/扣分规则。';
COMMENT ON TABLE history IS '操作历史表，记录积分、毕业、兑换和撤回等行为。';
COMMENT ON TABLE student_total_food_summaries IS '学生总食物构成汇总表，按学生和积分规则聚合历史累计获得的正向食物分。';
COMMENT ON TABLE shop_items IS '小卖部商品表，保存可兑换商品及库存信息。';
COMMENT ON TABLE exchange_records IS '兑换记录表，记录学生兑换商品的历史。';
COMMENT ON TABLE licenses IS '激活码表，用于注册激活和后台卡密管理。';

-- users 字段注释
COMMENT ON COLUMN users.id IS '用户主键，自增 ID。';
COMMENT ON COLUMN users.username IS '登录用户名，系统内唯一。';
COMMENT ON COLUMN users.password_hash IS '密码哈希值，使用 bcrypt 等方式加密存储。';
COMMENT ON COLUMN users.activation_code IS '最近一次绑定或使用的激活码。';
COMMENT ON COLUMN users.is_activated IS '账号是否已激活。';
COMMENT ON COLUMN users.is_admin IS '是否为系统管理员账号，拥有后台管理权限。';
COMMENT ON COLUMN users.settings IS '用户个性化设置，使用 JSONB 对象存储。';
COMMENT ON COLUMN users.created_at IS '记录创建时间。';
COMMENT ON COLUMN users.updated_at IS '记录最后更新时间。';

-- 默认管理员初始化
-- 首次进入后台后请尽快修改该管理员密码。
INSERT INTO users (
    username,
    password_hash,
    activation_code,
    is_activated,
    is_admin,
    settings
) VALUES (
    'admin',
    '$2b$10$6SAtk78Q.aQzItu/90OEwOaDPIXwIwkbuOE9TqxxB5U69vNbyDbna',
    NULL,
    TRUE,
    TRUE,
    '{}'::jsonb
)
ON CONFLICT (username) DO NOTHING;

-- classes 字段注释
COMMENT ON COLUMN classes.id IS '班级主键，自增 ID。';
COMMENT ON COLUMN classes.user_id IS '班级所属用户 ID，关联 users.id。';
COMMENT ON COLUMN classes.name IS '班级名称。';
COMMENT ON COLUMN classes.system_name IS '系统显示名称，例如石榴果宠物屋。';
COMMENT ON COLUMN classes.theme IS '班级主题标识。';
COMMENT ON COLUMN classes.growth_stages IS '宠物成长阶段阈值列表，使用 JSONB 数组存储。';
COMMENT ON COLUMN classes.sort_order IS '班级排序序号，数值越小越靠前。';
COMMENT ON COLUMN classes.created_at IS '记录创建时间。';
COMMENT ON COLUMN classes.updated_at IS '记录最后更新时间。';

-- groups 字段注释
COMMENT ON COLUMN groups.id IS '分组主键，自增 ID。';
COMMENT ON COLUMN groups.class_id IS '所属班级 ID，关联 classes.id。';
COMMENT ON COLUMN groups.name IS '分组名称。';
COMMENT ON COLUMN groups.sort_order IS '分组排序序号，数值越小越靠前。';
COMMENT ON COLUMN groups.created_at IS '记录创建时间。';
COMMENT ON COLUMN groups.updated_at IS '记录最后更新时间。';

-- students 字段注释
COMMENT ON COLUMN students.id IS '学生主键，自增 ID。';
COMMENT ON COLUMN students.class_id IS '所属班级 ID，关联 classes.id。';
COMMENT ON COLUMN students.name IS '学生姓名。';
COMMENT ON COLUMN students.pet_type IS '宠物类型标识，例如 white-cat。';
COMMENT ON COLUMN students.pet_name IS '宠物昵称。';
COMMENT ON COLUMN students.food_count IS '当前累计食物值/积分。';
COMMENT ON COLUMN students.food_reset_at IS '当前宠物食物分的清零时间；仅该时间之后的积分参与当前食物排行榜。';
COMMENT ON COLUMN students.total_food_earned IS '历史累计获得的正向食物分，用于总食物排行榜。';
COMMENT ON COLUMN students.badges IS '当前持有的可消费勋章列表，使用 JSONB 数组存储。';
COMMENT ON COLUMN students.current_badges_count IS '当前持有的可消费勋章数，用于勋章排行榜。';
COMMENT ON COLUMN students.total_badges_earned IS '历史累计获得的勋章总数，用于总勋章排行榜。';
COMMENT ON COLUMN students.sort_order IS '学生排序序号，数值越小越靠前。';
COMMENT ON COLUMN students.group_id IS '所属分组 ID，可为空，关联 groups.id。';
COMMENT ON COLUMN students.created_at IS '记录创建时间。';
COMMENT ON COLUMN students.updated_at IS '记录最后更新时间。';

-- score_rules 字段注释
COMMENT ON COLUMN score_rules.id IS '积分规则主键，自增 ID。';
COMMENT ON COLUMN score_rules.class_id IS '所属班级 ID，关联 classes.id。';
COMMENT ON COLUMN score_rules.name IS '积分规则名称。';
COMMENT ON COLUMN score_rules.icon IS '积分规则图标。';
COMMENT ON COLUMN score_rules.value IS '积分增减值，可正可负。';
COMMENT ON COLUMN score_rules.sort_order IS '规则排序序号，数值越小越靠前。';
COMMENT ON COLUMN score_rules.created_at IS '记录创建时间。';
COMMENT ON COLUMN score_rules.updated_at IS '记录最后更新时间。';

-- history 字段注释
COMMENT ON COLUMN history.id IS '历史记录主键，自增 ID。';
COMMENT ON COLUMN history.class_id IS '所属班级 ID，关联 classes.id。';
COMMENT ON COLUMN history.student_id IS '所属学生 ID，关联 students.id。';
COMMENT ON COLUMN history.rule_id IS '触发本次记录的积分规则 ID，可为空，不强制外键以保留历史。';
COMMENT ON COLUMN history.rule_name IS '触发本次记录的规则名称快照。';
COMMENT ON COLUMN history.value IS '本次变动值，正数表示增加，负数表示减少。';
COMMENT ON COLUMN history.type IS '记录类型：score、graduate、exchange、revoke。';
COMMENT ON COLUMN history.is_revoked IS '该历史记录是否已被撤回。';
COMMENT ON COLUMN history.created_at IS '记录创建时间。';
COMMENT ON COLUMN history.updated_at IS '记录最后更新时间。';

-- student_total_food_summaries 字段注释
COMMENT ON COLUMN student_total_food_summaries.id IS '汇总记录主键，自增 ID。';
COMMENT ON COLUMN student_total_food_summaries.class_id IS '所属班级 ID，关联 classes.id。';
COMMENT ON COLUMN student_total_food_summaries.student_id IS '所属学生 ID，关联 students.id。';
COMMENT ON COLUMN student_total_food_summaries.rule_id IS '积分规则 ID；不强制外键，便于规则删除后继续保留统计。';
COMMENT ON COLUMN student_total_food_summaries.rule_name IS '积分规则名称快照。';
COMMENT ON COLUMN student_total_food_summaries.award_count IS '该规则累计为学生贡献正向食物分的次数。';
COMMENT ON COLUMN student_total_food_summaries.total_food IS '该规则累计为学生贡献的正向食物分总数。';
COMMENT ON COLUMN student_total_food_summaries.created_at IS '记录创建时间。';
COMMENT ON COLUMN student_total_food_summaries.updated_at IS '记录最后更新时间。';

-- shop_items 字段注释
COMMENT ON COLUMN shop_items.id IS '商品主键，自增 ID。';
COMMENT ON COLUMN shop_items.class_id IS '所属班级 ID，关联 classes.id。';
COMMENT ON COLUMN shop_items.name IS '商品名称。';
COMMENT ON COLUMN shop_items.description IS '商品描述。';
COMMENT ON COLUMN shop_items.icon IS '商品图标。';
COMMENT ON COLUMN shop_items.price IS '兑换价格，单位为徽章数。';
COMMENT ON COLUMN shop_items.stock IS '库存数量，-1 表示不限库存。';
COMMENT ON COLUMN shop_items.created_at IS '记录创建时间。';
COMMENT ON COLUMN shop_items.updated_at IS '记录最后更新时间。';

-- exchange_records 字段注释
COMMENT ON COLUMN exchange_records.id IS '兑换记录主键，自增 ID。';
COMMENT ON COLUMN exchange_records.class_id IS '所属班级 ID，关联 classes.id。';
COMMENT ON COLUMN exchange_records.student_id IS '所属学生 ID，关联 students.id。';
COMMENT ON COLUMN exchange_records.item_id IS '兑换商品 ID，可为空，不强制外键以保留历史。';
COMMENT ON COLUMN exchange_records.item_name IS '兑换商品名称快照。';
COMMENT ON COLUMN exchange_records.cost IS '本次兑换消耗的徽章数量。';
COMMENT ON COLUMN exchange_records.created_at IS '记录创建时间。';
COMMENT ON COLUMN exchange_records.updated_at IS '记录最后更新时间。';

-- licenses 字段注释
COMMENT ON COLUMN licenses.id IS '激活码主键，自增 ID。';
COMMENT ON COLUMN licenses.code IS '激活码内容，系统内唯一。';
COMMENT ON COLUMN licenses.is_used IS '激活码是否已被使用。';
COMMENT ON COLUMN licenses.used_by IS '使用该激活码的用户 ID，可为空，关联 users.id。';
COMMENT ON COLUMN licenses.used_at IS '激活码使用时间。';
COMMENT ON COLUMN licenses.created_at IS '记录创建时间。';
COMMENT ON COLUMN licenses.updated_at IS '记录最后更新时间。';

COMMIT;
