BEGIN;

-- 兼容旧 PostgreSQL 库：如果之前不是通过 init-pgsql.sql 建库，这里先补上 updated_at 触发器函数。
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

ALTER TABLE students
    ADD COLUMN IF NOT EXISTS food_reset_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS total_food_earned INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS current_badges_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_badges_earned INTEGER NOT NULL DEFAULT 0;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_students_total_food_non_negative'
    ) THEN
        ALTER TABLE students
            ADD CONSTRAINT chk_students_total_food_non_negative CHECK (total_food_earned >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_students_current_badges_non_negative'
    ) THEN
        ALTER TABLE students
            ADD CONSTRAINT chk_students_current_badges_non_negative CHECK (current_badges_count >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_students_total_badges_non_negative'
    ) THEN
        ALTER TABLE students
            ADD CONSTRAINT chk_students_total_badges_non_negative CHECK (total_badges_earned >= 0);
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS student_total_food_summaries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id INTEGER NOT NULL,
    student_id INTEGER NOT NULL,
    rule_id INTEGER NOT NULL,
    rule_name VARCHAR(50) NOT NULL,
    award_count INTEGER NOT NULL DEFAULT 0,
    total_food INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_student_total_food_summaries_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    CONSTRAINT fk_student_total_food_summaries_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT uq_student_total_food_summaries_student_rule UNIQUE (class_id, student_id, rule_id),
    CONSTRAINT chk_student_total_food_summaries_award_count_positive CHECK (award_count > 0),
    CONSTRAINT chk_student_total_food_summaries_total_food_positive CHECK (total_food > 0)
);

CREATE INDEX IF NOT EXISTS idx_students_class_food_count ON students(class_id, food_count DESC);
CREATE INDEX IF NOT EXISTS idx_students_class_total_food_earned ON students(class_id, total_food_earned DESC);
CREATE INDEX IF NOT EXISTS idx_students_class_current_badges_count ON students(class_id, current_badges_count DESC);
CREATE INDEX IF NOT EXISTS idx_students_class_total_badges_earned ON students(class_id, total_badges_earned DESC);
CREATE INDEX IF NOT EXISTS idx_student_total_food_summaries_student_id ON student_total_food_summaries(student_id);
CREATE INDEX IF NOT EXISTS idx_student_total_food_summaries_class_student ON student_total_food_summaries(class_id, student_id);
CREATE INDEX IF NOT EXISTS idx_student_total_food_summaries_class_total_food ON student_total_food_summaries(class_id, total_food DESC);

DROP TRIGGER IF EXISTS trg_student_total_food_summaries_set_updated_at ON student_total_food_summaries;
CREATE TRIGGER trg_student_total_food_summaries_set_updated_at
BEFORE UPDATE ON student_total_food_summaries
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE student_total_food_summaries IS '学生总食物构成汇总表，按学生和积分规则聚合历史累计获得的正向食物分。';
COMMENT ON COLUMN students.food_reset_at IS '当前宠物食物分的清零时间；仅该时间之后的积分参与当前食物排行榜。';
COMMENT ON COLUMN students.total_food_earned IS '历史累计获得的正向食物分，用于总食物排行榜。';
COMMENT ON COLUMN students.current_badges_count IS '当前持有的可消费勋章数，用于勋章排行榜。';
COMMENT ON COLUMN students.total_badges_earned IS '历史累计获得的勋章总数，用于总勋章排行榜。';
COMMENT ON COLUMN student_total_food_summaries.id IS '汇总记录主键，自增 ID。';
COMMENT ON COLUMN student_total_food_summaries.class_id IS '所属班级 ID，关联 classes.id。';
COMMENT ON COLUMN student_total_food_summaries.student_id IS '所属学生 ID，关联 students.id。';
COMMENT ON COLUMN student_total_food_summaries.rule_id IS '积分规则 ID；不强制外键，便于规则删除后继续保留统计。';
COMMENT ON COLUMN student_total_food_summaries.rule_name IS '积分规则名称快照。';
COMMENT ON COLUMN student_total_food_summaries.award_count IS '该规则累计为学生贡献正向食物分的次数。';
COMMENT ON COLUMN student_total_food_summaries.total_food IS '该规则累计为学生贡献的正向食物分总数。';
COMMENT ON COLUMN student_total_food_summaries.created_at IS '记录创建时间。';
COMMENT ON COLUMN student_total_food_summaries.updated_at IS '记录最后更新时间。';

-- 当前勋章数可以从 badges JSON 可靠回填。
UPDATE students
SET current_badges_count = COALESCE(jsonb_array_length(badges), 0);

-- 历史上已经被消费掉的勋章在旧版本里没有单独流水，因此这里只能先按当前勋章数初始化总勋章。
UPDATE students
SET total_badges_earned = GREATEST(total_badges_earned, current_badges_count);

-- 总食物排行榜可以从“未撤回的正向 score 记录”直接回填。
WITH total_food AS (
    SELECT
        student_id,
        COALESCE(SUM(value), 0) AS total_food_earned
    FROM history
    WHERE type = 'score'
      AND is_revoked = FALSE
      AND value > 0
    GROUP BY student_id
)
UPDATE students s
SET total_food_earned = COALESCE(t.total_food_earned, 0)
FROM total_food t
WHERE s.id = t.student_id;

UPDATE students
SET total_food_earned = 0
WHERE total_food_earned IS NULL;

DELETE FROM student_total_food_summaries;

INSERT INTO student_total_food_summaries (
    class_id,
    student_id,
    rule_id,
    rule_name,
    award_count,
    total_food
)
SELECT
    h.class_id,
    h.student_id,
    h.rule_id,
    COALESCE(MAX(h.rule_name), '未命名规则') AS rule_name,
    COUNT(*) AS award_count,
    SUM(h.value) AS total_food
FROM history h
WHERE h.type = 'score'
  AND h.is_revoked = FALSE
  AND h.value > 0
  AND h.rule_id IS NOT NULL
GROUP BY h.class_id, h.student_id, h.rule_id;

COMMIT;
